### ISSUE TITLE
Performing DW-MRI simulations with spheres having different permeability

### ISSUE THREAD

**Issue by rochishnu00** [jonhrafe/MCDC_Simulator_public#5]
Is it possible to perform the monte carlo simulation on a substrate with a packing of spheres with two different permeabilities?

**Comment by jonhrafe** [comment]
Hey rochishnu00, 

To perform a simulation with packed spheres you will need to create a Mesh model since there's not a substrate as such implemented. This should not be really difficult and would work quite straightforward, however, for the permeability, I'm afraid the current version of the simulator only takes one global barrier permeability and doesn't support an individual coefficient per compartment/obstacle. 

This, however, should be relatively easy to implement and looks like a really useful issue to add.

**Comment by jonhrafe** [comment]
I'm adding this feature [in here]( https://github.com/jonhrafe/MCDC_Simulator_public/projects/1)
